- .gitignore
- .travis.yml
- README.md
- cypress.json
- index.js
- lib/error.js
- lib/graphql.js
- lib/with-defaults.js
- package-lock.json
- package.json
- test/defaults-test.js
- test/error-test.js
- test/graphql-test.js
> Initial version

- README.md
- lib/graphql.js
- test/error-test.js
Ref: https://github.com/octokit/graphql.js/issues/14
> Add test for handling partial data with error(s)

- README.md
Because the behavior of defaults is otherwise unclear. I didn't know until I read this: https://github.com/octokit/graphql.js/issues/12#issuecomment-474487694
> Update README.md to explain defaults behavior

- .travis.yml
Node 6 is no longer maintained and keeping dependencies up to date while supporting Node 6 is no longer manageable
> drop Node 6

- src/graphql.ts
- src/types.ts
- src/with-defaults.ts
@wolfy1339 I updated all dependencies / sub-dependencies and suddenly jest complained about typescript incompatibilities. I removed the Typescript parameters because I frankly did not understand them. Happy to bring them back, would love an explanation :) Just had to get this out of the way so I am no longer blocked on @octokit/core
> fix typescript errors in test

- src/types.ts
**Describe**
Use 
```TypeScript
ReturnType<typeof graphql>
```
so we don't have to manually change the overload return types as they are changed in `graphql.ts`
> Improve return type on `graphql` overloads

- src/types.ts
The jsdoc for the `graphql(query, options)` method overload specified the
first argument as a route, when it's really a GraphQL query. This
updates the documentation to reflect that.
This also adds a line to the `graphql(options)` method overload that
specifies that the GraphQL query must be specified in the `options`
parameter. If that's superfluous or could be documented better I'm happy to change it.
Closes #49
> docs(types): document query argument in graphql interface

- src/error.ts
- src/graphql.ts
- src/types.ts
- src/with-defaults.ts
This adds support for an optional generic to the graphql function exported by octokit/@graphql. If no type is passed, the return type will be an object with `string` keys and `any` values.
As far as generic naming goes, I went with `ResponseData`, since I thought it'd be a little more descriptive than `T`,  but I can also change that if that's more aligned with TypeScript conventions.
Without a generic
Closes #80
> feat(typescript): add generic support to graphql 

- src/error.ts
- src/graphql.ts
- test/error.test.ts
This fixes #158.
After this change, the exception thrown has this structure:
```json
{
"errors": [
{
"path": ["query", "viewer", "bioHtm"],
"extensions": {
"code": "undefinedField",
"typeName": "User",
"fieldName": "bioHtm"
},
"locations": [{ "line": 4, "column": 11 }],
"message": "Field 'bioHtm' doesn't exist on type 'User'"
}
],
"headers": {
"access-control-allow-origin": "*",
"access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
"cache-control": "no-cache",
"connection": "close",
"content-encoding": "gzip",
"content-security-policy": "default-src 'none'",
"content-type": "application/json; …
```
> fix: set error.headers from responses containing a GraphQL error

- README.md
There're some syntax error caused by missing comma or extra bracket in the readme. This PR fixes that.
> fix: syntax error in the code example

- src/graphql.ts
- test/defaults.test.ts
fixes #185
fixes https://github.com/octokit/auth-app.js/issues/111
/cc @lencioni
> fix: handle `baseUrl` suffix for GHES

- src/graphql.ts
- test/graphql.test.ts
> fix: throw helpful error when `query` is used as variable name

- README.md
- src/index.ts
Expose GraphQlQueryResponseData type
Fix #254
> feat(types): expose GraphQlQueryResponseData type

- README.md
The package doesn't seem to export `endpoint`
> Update browser import

- src/graphql.ts
- test/graphql.test.ts
> fix: throw helpful error in case "query", "url", or "method" is used as query variable

- src/types.ts
GraphQL response errors can have a `type` field that can be useful
for error detection. e.g. if a pull request does not exist there is
an error with the `NOT_FOUND` type.
@gr2m maybe you could help with this here. I have not found any official specification from Github on this, but I see feature requests for this in other Github GraphQL libraries and I can see it in various requests from Github. We could also type this as potentially `undefined`? I lack information here unfortunately.
> feat(typescript): expose `type` property for errors in graphql response errors

- README.md
The option passed to `createAppAuth` should be `appId` instead if `id`
> docs(README): fix app auth example

- README.md
The correct name of the header is 'Authorization' and not 'Authentication'. 
Tested with: 
```
curl -H "Authorization: bearer {edited}" -X POST -d " \
{ \
\"query\": \"query { viewer { login }}\" \
} \
" https://api.github.com/graphql
```
Previously:
```
$ curl -H "Authentication: bearer {edited}" -X POST -d " \
{ \
\"query\": \"query { viewer { login }}\" \
} \
" https://api.github.com/graphql
{
"message": "This endpoint requires you to be authenticated.",
"documentation_url": "https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql"
}
```
> fix(docs): refer to `Authorization` header in the README, not `Authentication`

- package-lock.json
- package.json
- scripts/build.mjs
- src/error.ts
- src/graphql.ts
- src/index.ts
- src/types.ts
- src/with-defaults.ts
- test/error.test.ts
- test/graphql.test.ts
- tsconfig.json
Pika has been deprecated for a while now, and the project has now been archived, and because of that any released npm package is missing most of the files generated by the build step.
Uses esbuild to transpile the TS source code into an ESM source, NodeJs bundle, and a browser bundle
Uses the TypeScript compiler to generate the types
----
* Uses pika for the build system
* The released npm package would be missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.
* Uses esbuild to generate the JS bundles
* Uses the TypeScript compiler to generate the type definitions
* The correct file matching patterns are used so we publish all the necessary files.
* See #583, …
> fix(build): replace pika with esbuild and tsc

- package.json
- scripts/build.mjs
- src/error.ts
- src/graphql.ts
- src/index.ts
- src/types.ts
- src/with-defaults.ts
- test/tsconfig.test.json
This PR replaces NodeJS internal module imports with `node:` specifier imports.
> refactor: use `node:` specifier imports and full relative path imports

- README.md
- package-lock.json
- package.json
- scripts/build.mjs
- src/index.ts
- test/graphql.test.ts
- test/tsconfig.test.json
BREAKING CHANGE: this package is now ESM
> feat: package is now ESM

- scripts/build.mjs
Resolves octokit/core.js#667 
Resolves octokit/core.js#665
Partly reverts #551
---
- Some consumers of this package could not resolve it properly (ex: `jest`, `ts-node`, `tsx`)
- CJS consumers would be getting errors even though the package is ESM
- Consumers cannot import paths from the package like in CJS
- Clients should be able to import the module without any errors with the fallback
- CJS consumers will generate a better error with the new fallback
- Consumers are able to import types from the `dist-types/types.d.ts` file in the package
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
---
> fix(pkg): add `default` fallback and `types` export

- package-lock.json
- package.json
See https://github.com/octokit/octokit.js/issues/2762#issuecomment-2486997620
Resolves #ISSUE_NUMBER
----
* Types would include a reference to `@types/node` even though there is nothing using Node specific APIs in the types
* Update `@octokit/types` to make sure types are platform agnostic
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> fix(deps): bump Octokit dependencies

- package-lock.json
- package.json
- src/graphql.ts
- test/defaults.test.ts
- test/graphql.test.ts
Resolves #406
Related types PR: https://github.com/octokit/types.ts/pull/662
----
* It was not possible to send a query with multiple operations
* Sending a query with multiple operations
* Specifying to the server which operation to use
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> Allow users to specify `operationName` in multi-operation queries

- .github/workflows/update-prettier.yml
Resolves #ISSUE_NUMBER
----
* Used Node 16 for the `update-prettier` workflow
* Use Node LTS instead of pinning to a specific version
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
> ci(prettier): use Node LTS instead of v16
